name: whitespace
version: 0.2.0.0
license: MIT

dependencies:
  - base >= 4.11 && < 5
  - rio # TODO

ghc-options:
  - -Weverything
  - -Wno-missing-import-lists
  - -Wno-missing-kind-signatures
  - -Wno-missing-poly-kind-signatures
  - -Wno-missing-role-annotations
  - -Wno-missing-safe-haskell-mode
  - -Wno-unsafe

language: GHC2021

default-extensions:
  - DataKinds
  - DeriveAnyClass
  - DerivingStrategies
  - DerivingVia
  - DuplicateRecordFields
  - GADTs
  - LambdaCase
  - NoFieldSelectors
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - NoPostfixOperators
  - OverloadedRecordDot
  - OverloadedStrings
  - QuasiQuotes
  - TypeFamilies

library:
  source-dirs: src

executables:
  whitespace:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - optparse-applicative
      - whitespace

tests:
  whitespace-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspec
      - whitespace
